[build]
  functions = "netlify/functions"

[[headers]]
  # Ensure basic security headers are applied to whole site
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
